"""
ConversationState schema for multi-agent customer support system.

This state is shared across all agents in the LangGraph workflow and persists
between agent transitions. All agents read from and update this state.
"""

from typing import Optional, TypedDict


class ConversationState(TypedDict):
    """
    Shared conversation state managed by LangGraph.
    
    This state is passed between agents and updated throughout the conversation
    lifecycle. All fields are optional except user_message to allow for
    progressive state building as the conversation flows.
    """
    
    # Current user input message
    user_message: str
    
    # Customer email address (identified or requested by orchestrator)
    customer_email: Optional[str]
    
    # Full customer profile data retrieved from customers.csv
    # Contains: customer_id, name, plan_type, tier, account_health_score, etc.
    customer_data: Optional[dict]
    
    # Classified intent from orchestrator agent
    # Values: 'cancel_insurance', 'technical_issue', 'billing_question', 'general_question'
    intent: Optional[str]
    
    # Reason for cancellation (if intent is cancel_insurance)
    # Examples: 'financial_hardship', 'product_issues', 'service_value'
    cancellation_reason: Optional[str]
    
    # List of retrieved document chunks from RAG queries
    # Each string is a relevant snippet from policy documents
    retrieved_context: list[str]
    
    # Retention offer generated by retention agent
    # Contains offer details: type, cost, duration, description, authorization
    retention_offer: Optional[dict]
    
    # Final action taken by processor agent
    # Values: 'cancelled', 'retained', 'routed_to_support', 'routed_to_billing', etc.
    final_action: Optional[str]

